### ISSUE TITLE
Dont't append to a json response

### ISSUE THREAD

**Issue by BramRoets** [viacreative/sudo-su#6] opened 2017-03-23 08:00 UTC
It seems that the plugin appends itself to every response, including a json response. This breaks a lot of things.

(Laravel 5.3)

**Comment by krve** [comment] 2017-03-23 08:03
Duplicate of #4 

A pull request has been made to fix the issue: #3

**Comment by mrterryh** [comment] 2017-03-23 08:21
Yep, just merged that PR. Credit to @krve for the fix! :+1:

**Closed by mrterryh** 2017-03-23 08:21 UTC

**Comment by BramRoets** [comment] 2017-03-23 11:15
This fix won't cover all cases. When developing I open a chrome tab showing a json response. 

 `$request->expectsJson()`Will return false, but i'm still watching a json response. You should detect when the json response header is set.

**Comment by krve** [comment] 2017-03-23 11:16
The PR moved away from using middleware and instead uses a view you have to include.

**Comment by BramRoets** [comment] 2017-03-23 11:20
Oh okay, I missed that :) Thanks for implementing the fix!
